spring:
  application:
    name: todo

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5435/todo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /todo