version: "3"
services:
  postgres-develop:
    image: postgres:latest
    container_name: postgres-develop
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5433:5432"
    volumes:
      - postgres_develop_data:/var/lib/postgresql/data

  postgres-staging:
    image: postgres:latest
    container_name: postgres-staging
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5434:5432"
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data

  postgres-production:
    image: postgres:latest
    container_name: postgres-production
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5435:5432"
    volumes:
      - postgres_production_data:/var/lib/postgresql/data

volumes:
  postgres_develop_data:
  postgres_staging_data:
  postgres_production_data:
