spring:
  application:
    name: todo
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/todo
    user: postgres
    password: postgres
    locations: classpath:db/migration