spring:
  application:
    name: todo

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5433/todo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    com.example.todo.repository: DEBUG
    org:
      springframework:
        web=DEBUG: