spring:
  application:
    name: todo
  logging:
    level:
      org:
        flywaydb: DEBUG
  datasource:
    url: jdbc:postgresql://localhost:5433/todo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
