spring:
  application:
    name: todo

  flyway:
    enabled: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: jdbc:postgresql://postgres-staging:5434/todo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.web: DEBUG